development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: letsmeet_development
  pool:     5
  username: postgres
  password:
  template: template0

test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: letsmeet_test
  pool:     5
  username: postgres
  password:
  template: template0

production:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: letsmeet_production
  pool:     5
  username: postgres
  password:
  template: template0
